In [5]:
# 1.a) Create a variable named var1 that stores an array of numbers from 0 to 30,inclusive. Print var1 and its shape. Hint : arange
import numpy as np

# Creating var1 as an array of numbers from 0 to 30 inclusive
var1 = np.arange(31)
print("var1:", var1)
print("Shape of var1:", var1.shape)


var1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape of var1: (31,)


In [6]:
# b) Change var2 to a validly-shaped two-dimensional matrix and store it in a new variable called var2. Print var2 and its shape. Hint: Use the reshape function
# Reshape var1 into a 2D matrix and store it in var2
var2 = var1.reshape(1, 31)  
print("var2:\n", var2)
print("Shape of var2:", var2.shape)


var2:
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30]]
Shape of var2: (1, 31)


In [7]:
# Create a third variable, var3 that reshapes it into a valid three-dimensional shape.Print var3 and its shape.
# Reshape var2 into a 3D shape for var3
var3 = var1.reshape(1, 1, 31) 
print("var3:\n", var3)
print("Shape of var3:", var3.shape)


var3:
 [[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
   23 24 25 26 27 28 29 30]]]
Shape of var3: (1, 1, 31)


In [8]:
# d) Use two-dimensional array indexing to set the first value in the second row of var2 to -1. Now look at var1 and var3. Did they change? Explain what’sgoing on. (Hint: does reshape return a view or a copy?)
# Reshape var1 into a shape with at least two rows for var2
var2 = var1[:30].reshape(5, 6) 
print("Original var2:\n", var2)

# Set the first value in the second row of var2 to -1
var2[1, 0] = -1
print("\nModified var2:\n", var2)

# Check if var1 and var3 are affected
print("\nUpdated var1:", var1)
print("\nUpdated var3:\n", var3)


Original var2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Modified var2:
 [[ 0  1  2  3  4  5]
 [-1  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Updated var1: [ 0  1  2  3  4  5 -1  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]

Updated var3:
 [[[ 0  1  2  3  4  5 -1  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
   23 24 25 26 27 28 29 30]]]


In [9]:
# e) Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the NumPy sum function works (and the axis argument in particular) and do the following:
#(i) Sum var3 over its second dimension and print the result.
#ii) Sum var3 over its third dimension and print the result.
#(iii) Sum var3 over both its first and third dimensions and print the result.
import numpy as np
# (i) Sum var3 over its second dimension (axis=1)
sum_var3_axis_1 = np.sum(var3, axis=1)
print("Sum of var3 over its second dimension:\n", sum_var3_axis_1)

# (ii) Sum var3 over its third dimension (axis=2)
sum_var3_axis_2 = np.sum(var3, axis=2)
print("\nSum of var3 over its third dimension:\n", sum_var3_axis_2)

# (iii) Sum var3 over both its first and third dimensions (axes=0 and 2)
sum_var3_axis_0_2 = np.sum(var3, axis=(0, 2))
print("\nSum of var3 over both its first and third dimensions:\n", sum_var3_axis_0_2)



Sum of var3 over its second dimension:
 [[ 0  1  2  3  4  5 -1  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30]]

Sum of var3 over its third dimension:
 [[458]]

Sum of var3 over both its first and third dimensions:
 [458]


In [13]:
# f) Write code to do the following:
#(i) Slice out the second row of var2 and print it.
#(ii) Slice out the last column of var2 using the -1 notation and print it.
#(iii) Slice out the top right 2 × 2 submatrix of var2 and print it.
# Assuming var2 is reshaped as a 2D array with multiple rows and columns, such as
# var2 = var1[:30].reshape(5, 6)  # 5 rows and 6 columns for example

# (i) Slice out the second row of var2 and print it
second_row_var2 = var2[1, :]
print("Second row of var2:\n", second_row_var2)

# (ii) Slice out the last column of var2 using the -1 notation and print it
last_column_var2 = var2[:, -1]
print("\nLast column of var2:\n", last_column_var2)

# (iii) Slice out the top-right 2x2 submatrix of var2 and print it
top_right_2x2_var2 = var2[:2, -2:]
print("\nTop-right 2x2 submatrix of var2:\n", top_right_2x2_var2)


Second row of var2:
 [-1  7  8  9 10 11]

Last column of var2:
 [ 5 11 17 23 29]

Top-right 2x2 submatrix of var2:
 [[ 4  5]
 [10 11]]


In [14]:
# 2.a) The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that operation with the scalar for every element of the array. To try this out, create a vecto1, 2, . . . , 10 by adding 1 to the result of the arange function.
import numpy as np

# Create a vector from 1 to 10 by adding 1 to np.arange(10)
vector = np.arange(10) + 1
print("Vector:", vector)


Vector: [ 1  2  3  4  5  6  7  8  9 10]


In [15]:
# b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this using the vector you just created, and adding it to a reshaped version of itself.
import numpy as np

# Create a vector from 0 to 9 (to represent row and column indices)
vector = np.arange(10)

# Create the 10x10 matrix A by adding the vector to a reshaped version of itself
A = vector.reshape(10, 1) + vector
print("Matrix A:\n", A)


Matrix A:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


In [16]:
# c) A very common use of broadcasting is to standardize data, i.e., to make it have zero mean and unit variance. First, create a fake “data set” with 50 examples, each with five dimensions. 
#import numpy.random as npr
#data = np.exp(npr.randn ( 50 , 5 ) )
import numpy as np
import numpy.random as npr
data = np.exp(npr.randn(50, 5))
print("Data:\n", data)
print("Shape of data:", data.shape)


Data:
 [[ 1.7575948   1.21262152  5.18733718  1.04322924  1.65253964]
 [ 7.58730456  1.16049353  2.32099667  0.32249622  0.44182592]
 [ 0.39330305  2.37081717  1.4875228   5.13151131  0.85949488]
 [ 5.37519096  2.02101472  0.54164651  0.22907548  1.01527004]
 [ 0.49728083  1.83017711  1.89323377  2.43386294  0.25423171]
 [ 0.05115681  0.87922028  0.77574092 17.91702849  0.0298899 ]
 [ 2.21543465  0.44522924  0.46829672  2.857492    0.0635069 ]
 [ 2.37807656  0.72405527  2.01520804  0.17710481  5.58666658]
 [ 0.70743707  5.40737073  0.57885385  0.23010584  0.3484044 ]
 [ 0.66887958  0.89047061  0.54701644  0.57042603  1.07062342]
 [ 0.23617307  0.4016663   3.38826224  0.40466943  2.41333979]
 [ 0.74183737  0.79224436  0.99526576  1.81229042  0.21336006]
 [ 2.36128782  0.65212371  0.3454856   1.74923406 15.68931682]
 [ 1.08353569  0.93791083  1.35533929  1.22781704  2.42166778]
 [ 2.3178838   2.73896794  0.82815568  1.09948248  7.27222313]
 [ 0.22650191  2.62237494  1.7317306   1.9214396

In [17]:
# You don’t worry too much about what this code is doing at this stage of the course, but for completeness: it imports the NumPy random number generation library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend data set of 50 independent and identically-distributed vectors from a log-normal distribution.
import numpy as np
import numpy.random as npr

# Generate a 50 × 5 matrix of standard normal random variates
data = np.exp(npr.randn(50, 5))

# Display the dataset and its shape
print("Data:\n", data)
print("Shape of data:", data.shape)


Data:
 [[ 1.99728764  1.29207965  1.32587251  1.4635516   0.56306778]
 [ 1.24347298  1.46966105  1.71266711  0.31390776  0.57694726]
 [ 3.00307227  0.42213777  0.9450234   2.49202732  1.3243223 ]
 [ 0.85761089  0.21583518  3.37154405  1.90436589  3.36540426]
 [ 2.246045    2.00019762  1.06718097  1.15532017  0.47229397]
 [ 1.36543367  6.31349589  1.50181922  1.62325083  0.85769416]
 [ 0.30323509  1.64183692 16.50687195  0.51217961  0.40167084]
 [ 2.70582739  0.69805782  1.51581583  1.26440495  1.23496053]
 [ 0.78862991  0.83987877  1.11054494  0.10502431  0.94253291]
 [ 2.48052856 10.01545334  2.55102892  2.28467313  3.49525425]
 [ 2.74478075  3.80672983  0.3365617   1.37899735  2.47617397]
 [ 1.16794107  1.32455772  0.55130649  0.83700388  1.49508825]
 [ 1.59094692  0.71239914  1.32435579  0.60604025  0.76923623]
 [ 1.33828131  3.69752511  0.46191203  0.43467688  0.77735828]
 [ 1.54517951  0.31480907  0.21559954  1.95485711  0.91511206]
 [ 0.69666755  2.65129708  0.35683305  0.7354298

In [18]:
# e) Now, compute the mean and standard deviation of each column. This should result in two vectors of length 5. You’ll need to think a little bit about how to use the axis argument to mean and std. Store these vectors into variables and print both of them.
# Calculate the mean of each column
mean_values = np.mean(data, axis=0)

# Calculate the standard deviation of each column
std_values = np.std(data, axis=0)
print("Mean of each column:\n", mean_values)
print("Standard deviation of each column:\n", std_values)


Mean of each column:
 [1.40256037 1.80991193 1.95130317 1.35514219 1.68322781]
Standard deviation of each column:
 [1.08372726 1.81225722 2.64792693 1.06661802 1.71845979]


In [19]:
# f) Now standardize the data matrix by 1) subtracting the mean off of each column, and 2) dividing each column by its standard deviation. Do this via broadcasting, and store the result in a matrix called normalized. To verify that you successfully did it, compute the mean and standard deviation of the columns of normalized and print them out.

normalized = (data - mean_values) / std_values
normalized_mean = np.mean(normalized, axis=0)
normalized_std = np.std(normalized, axis=0)
print("Normalized Data:\n", normalized)
print("Mean of each column in normalized data:\n", normalized_mean)
print("Standard deviation of each column in normalized data:\n", normalized_std)


Normalized Data:
 [[ 0.54877947 -0.28573884 -0.23619635  0.10163845 -0.65183953]
 [-0.14679652 -0.18774977 -0.09012184 -0.97620181 -0.64376284]
 [ 1.47685858 -0.76577107 -0.38002551  1.06587842 -0.20885301]
 [-0.50284744 -0.87960844  0.53635954  0.51492071  0.97888613]
 [ 0.77831818  0.10499927 -0.33389222 -0.18734169 -0.7046623 ]
 [-0.03425834  2.48506885 -0.16974938  0.25136331 -0.4803916 ]
 [-1.01439294 -0.09274346  5.49696769 -0.79031346 -0.74575906]
 [ 1.20257843 -0.61351893 -0.1644635  -0.08507004 -0.26085409]
 [-0.56649905 -0.53526241 -0.31751565 -1.17203897 -0.43102253]
 [ 0.99468587  4.52780175  0.22648878  0.871475    1.05444797]
 [ 1.23852231  1.10184022 -0.60981346  0.02236523  0.46142841]
 [-0.21649294 -0.2678175  -0.52871424 -0.48577682 -0.1094815 ]
 [ 0.17383207 -0.60560542 -0.23676914 -0.70231511 -0.53186672]
 [-0.05931295  1.04158127 -0.56247441 -0.86297559 -0.52714037]
 [ 0.13160058 -0.82499484 -0.65549529  0.56225839 -0.44697918]
 [-0.65135652  0.46427469 -0.6021579 

In [20]:
# 3. a)
import numpy as np

def vandermonde(N):
    vec = np.arange(N) + 1  # Create the vector [1, 2, ..., N]
    # Create the Vandermonde matrix using broadcasting
    V = vec[:, np.newaxis] ** np.arange(N)  # Broadcasting
    return V

# Use the function for N = 12
vander = vandermonde(12)
print("Vandermonde Matrix:\n", vander)


Vandermonde Matrix:
 [[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 

In [21]:
# b) Now, let’s make a pretend linear system problem with this matrix. Create a vector of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of vander with the vector you just created and store that in a new vector and call it b.
#Print the vector b.

# Create a vector of all ones, length 12
x = np.ones(12)

# Perform matrix-vector multiplication
b = np.dot(vander, x)

# Print the resulting vector b
print("Vector b:\n", b)


Vector b:
 [1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


In [22]:
# c) First, solve the linear system the naïve way, pretending like you don’t know x.
#Import numpy.linalg, invert V and multiply it by b. Print out your result. What should you get for your answer? If the answer is different than what you expected, write a sentence about that difference.
import numpy as np
import numpy.linalg as linalg

# Solve the linear system using the naive method
V_inv = linalg.inv(vander)  
x_solution = np.dot(V_inv, b) 

# Print the resulting x_solution
print("Estimated x:\n", x_solution)


Estimated x:
 [-12.26953125   5.90625     15.421875    -6.03515625   2.05859375
   0.92675781   1.00244141   1.00010681   0.99997711   1.00000131
   0.99999996   1.        ]


In [23]:
# d) Now, solve the same linear system using solve. Print out the result. Does it seem more or less in line with what you’d expect?
# Solve the linear system using np.linalg.solve
x_solution_solve = linalg.solve(vander, b)

# Print the resulting x_solution from solve
print("Estimated x using np.linalg.solve:\n", x_solution_solve)


Estimated x using np.linalg.solve:
 [0.98080503 1.05139768 0.94513807 1.03151945 0.98899166 1.00248816
 0.99962407 1.0000384  0.99999737 1.00000012 1.         1.        ]
